POST http://localhost:5135/api/donors
Content-Type: application/json

{
  "firstName": "Samuel",
  "lastName": "Burg",
  "email": "samuelburg@gmail.com",
  "address": {
    "street": "Rua Pedro 123",
    "postalCode": "884000",
    "city": "Ituporanga",
    "state": "SC"
  },
  "weight": "75.0",
  "birth": "1999-10-01"
}