POST http://localhost:5135/api/donors
Content-Type: application/json

{
  "firstName": "Marcionei",
  "lastName": "Eyng",
  "email": "meyng@gmail.com",
  "address": {
    "street": "Rua Pedro 123",
    "postalCode": "88400000",
    "city": "",
    "state": ""
  },
  "weight": "85",
  "birth": "1989-10-01",
  "bloodType": 1,
  "bloodRhFactor": 2,
  "genre": 0
}